# Generated by Django 3.0.6 on 2020-08-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullUps', '0003_auto_20200626_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excerciseblock',
            old_name='excercise',
            new_name='ExcerciseSet',
        ),
        migrations.RenameField(
            model_name='excerciseblock',
            old_name='breakTime',
            new_name='breakTimeAfterBlock',
        ),
        migrations.RenameField(
            model_name='excerciseset',
            old_name='reps',
            new_name='breakTimeAfterSet',
        ),
        migrations.RemoveField(
            model_name='excerciseblock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='excerciseblock',
            name='repsNumber',
        ),
        migrations.AddField(
            model_name='excerciseset',
            name='repsSet',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
