# Generated by Django 3.0.6 on 2020-08-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullUps', '0004_auto_20200806_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excerciseblock',
            old_name='ExcerciseSet',
            new_name='usedExcerciseSet',
        ),
        migrations.RenameField(
            model_name='excerciseset',
            old_name='repsSet',
            new_name='repsCount',
        ),
        migrations.AddField(
            model_name='excerciseblock',
            name='countOfSets',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
