# Generated by Django 3.0.6 on 2020-08-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pullUps', '0005_auto_20200826_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excerciseblock',
            old_name='usedExcerciseSet',
            new_name='usedExcerciseSets',
        ),
        migrations.RemoveField(
            model_name='excerciseblock',
            name='countOfSets',
        ),
    ]
