# Generated by Django 3.0.6 on 2020-10-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullUps', '0006_auto_20200827_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
