# Generated by Django 3.0.6 on 2020-10-15 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pullUps', '0008_auto_20201012_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excerciseblock',
            name='usedExcerciseSets',
            field=models.ManyToManyField(blank=True, through='pullUps.ExcerciseBlockSets', to='pullUps.ExcerciseSet'),
        ),
        migrations.AlterField(
            model_name='excerciseblocksets',
            name='blockKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pullUps.ExcerciseBlock'),
        ),
        migrations.AlterField(
            model_name='excerciseblocksets',
            name='setKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pullUps.ExcerciseSet'),
        ),
    ]
