# Generated by Django 3.0.6 on 2020-06-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullUps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excercise',
            name='name',
            field=models.TextField(default='Cwicz'),
            preserve_default=False,
        ),
    ]
