# Generated by Django 3.0.6 on 2020-06-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pullUps', '0002_excercise_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcerciseBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repsNumber', models.IntegerField()),
                ('breakTime', models.IntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('blocks', models.ManyToManyField(to='pullUps.ExcerciseBlock')),
            ],
        ),
        migrations.CreateModel(
            name='ExcerciseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('usedExcercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pullUps.Excercise')),
            ],
        ),
        migrations.AddField(
            model_name='excerciseblock',
            name='excercise',
            field=models.ManyToManyField(to='pullUps.ExcerciseSet'),
        ),
    ]
